import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hydrated_bloc/hydrated_bloc.dart';
import 'package:rock_and_morty_freezed_flutter/data/models/character.dart';
import 'package:rock_and_morty_freezed_flutter/data/repository/character_repo.dart';

part 'character_bloc.freezed.dart'; //generated by freezed
part 'character_bloc.g.dart'; //generated by json_serializable
part 'character_event.dart';
part 'character_state.dart';

class CharacterBloc extends Bloc<CharacterEvent, CharacterState>
    with HydratedMixin {
  final CharacterRepo characterRepo;

  CharacterBloc({required this.characterRepo})
      : super(const CharacterState.loading()) {
    on<CharacterEventFetch>((event, emit) async {
      emit(const CharacterState.loading());

      try {
        Character _characterLoaded = await characterRepo
            .getCharacter(event.page, event.name)
            .timeout(const Duration(seconds: 5));
        emit(CharacterState.loaded(characterLoaded: _characterLoaded));
      } catch (_) {
        emit(const CharacterState.error());
        // rethrow;
      }
    });
  }

  //load state
  @override
  CharacterState? fromJson(Map<String, dynamic> json) =>
      CharacterState.fromJson(json);

  //save state
  @override
  Map<String, dynamic>? toJson(CharacterState state) => state.toJson();
}
